name: PlayTime
author: F64_Rx
version: ${project.version}
api-version: 1.13
description: ${project.description}
main: me.f64.playtime.Main
depend: [ PlaceholderAPI ]

commands:
  playtime:
    usage: /<command>
    aliases: [ timeplayed, pt ]
    description: Main command for Playtime!
